In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv('pks.csv')

In [5]:
data.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

In [7]:
data = data.rename(columns = {'class': 'Class'})
data.dropna(inplace=True)
data.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,Class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

In [9]:
X = data.drop(['id','Class'], axis=1)
y = data['Class']

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.5)

In [11]:
from sklearn.svm import SVC
model1=SVC()
model1.fit(x_train, y_train)
model1.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

0.7354497354497355

In [12]:
from sklearn.naive_bayes import GaussianNB
model2=GaussianNB()
model2.fit(x_train, y_train)
model2.score(x_test, y_test)

0.7301587301587301

In [13]:
from sklearn.neighbors import KNeighborsClassifier
model4 = KNeighborsClassifier()
model4.fit(x_train, y_train)
model4.score(x_test,y_test)

0.6878306878306878

In [14]:
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(x_train, y_train)
model3.score(x_test, y_test)

0.7857142857142857

In [16]:
#Correlation Calculation

df1 = X
op=y
a1=[]
c1=[]

for i in df1.columns.values:
    correlation=op.corr(df1[i])
    if correlation>0.2:
        #print(correlation)
        a1.append(correlation)
        c1.append(i)

dfc1=pd.DataFrame(c1)
dfa1=pd.DataFrame(a1)
info1 = pd.concat([dfc1,dfa1], axis=1)
info1.columns = ['name','correlation']
info1

                         name  correlation
0                         DFA     0.306070
1                        RPDE     0.247444
2            meanPeriodPulses     0.211368
3                locPctJitter     0.204228
4                apq11Shimmer     0.227427
..                        ...          ...
69       tqwt_minValue_dec_16     0.244959
70  tqwt_kurtosisValue_dec_18     0.208645
71  tqwt_kurtosisValue_dec_20     0.225739
72  tqwt_kurtosisValue_dec_35     0.219454
73  tqwt_kurtosisValue_dec_36     0.279827

[74 rows x 2 columns]

In [17]:
top1 = info1.nlargest(50,'correlation')
SelectedFeatures1= np.array(top1['name'])
SelectedFeatures1

array(['mean_MFCC_2nd_coef', 'tqwt_minValue_dec_12',
       'tqwt_minValue_dec_11', 'tqwt_minValue_dec_13',
       'std_9th_delta_delta', 'std_8th_delta_delta',
       'std_7th_delta_delta', 'std_6th_delta_delta', 'std_8th_delta',
       'std_10th_delta_delta', 'std_9th_delta', 'std_11th_delta_delta',
       'std_6th_delta', 'std_7th_delta', 'std_delta_delta_log_energy',
       'tqwt_minValue_dec_14', 'std_10th_delta', 'std_11th_delta', 'DFA',
       'std_12th_delta_delta', 'tqwt_minValue_dec_10',
       'app_entropy_shannon_10_coef', 'app_entropy_shannon_9_coef',
       'app_entropy_shannon_8_coef', 'app_entropy_shannon_7_coef',
       'app_entropy_shannon_6_coef', 'app_entropy_shannon_5_coef',
       'app_entropy_shannon_4_coef', 'app_entropy_shannon_3_coef',
       'app_entropy_shannon_2_coef', 'app_entropy_shannon_1_coef',
       'std_12th_delta', 'tqwt_kurtosisValue_dec_36',
       'tqwt_entropy_log_dec_26', 'std_4th_delta_delta', 'std_4th_delta',
       'tqwt_minValue_dec_15', 'tqwt_entropy_log_dec_27',
       'std_5th_delta_delta', 'app_LT_entropy_shannon_6_coef',
       'app_LT_entropy_shannon_8_coef', 'app_LT_entropy_shannon_9_coef',
       'app_LT_entropy_shannon_10_coef', 'app_LT_entropy_shannon_5_coef',
       'std_delta_log_energy', 'app_LT_entropy_shannon_7_coef',
       'app_LT_entropy_shannon_4_coef', 'std_5th_delta',
       'tqwt_minValue_dec_7', 'app_LT_entropy_shannon_3_coef'],
      dtype=object)

In [18]:
#Information Gain Ratio Calculation

from collections import Counter
from scipy.stats import entropy
import math


def info_gain(Ex, a, nan=True):
    
    # Check whether examples and attributes have the same lengths.
    if len(Ex) != len(a):
        raise ValueError("Ex and a must be of the same size.")

    # Compute the entropy of examples
    H_Ex = entropy(list(Counter(Ex).values()))

    # If nan is True, replace all nan values in a by the string "__nan__"
    if nan:
        a = ['__nan__' if isinstance(x, float) and math.isnan(x) else x for x in a]
    
    # Compute the sum of all values v in a
    sum_v = 0
    for v in set(a):
        Ex_a_v = [x for x, t in zip(Ex, a) if t == v]
        sum_v += (len(Ex_a_v) / len(Ex)) *\
                 (entropy(list(Counter(Ex_a_v).values())))

    # Return result
    return H_Ex - sum_v


def intrinsic_value(Ex, a, nan=True):
    
    # Check whether examples and attributes have the same lengths.
    if len(Ex) != len(a):
        raise ValueError("Ex and a must be of the same size.")

    # If nan is True, replace all nan values in a by the string "__nan__"
    if nan:
        a = ['__nan__' if isinstance(x, float) and math.isnan(x) else x for x in a]
                
    # Compute the sum of all values v in a
    sum_v = 0
    for v in set(a):
        Ex_a_v = [x for x, t in zip(Ex, a) if t == v]
        sum_v += (len(Ex_a_v) / len(Ex)) * math.log(len(Ex_a_v) / len(Ex), 2)

    # Return result
    return -sum_v


def info_gain_ratio(Ex, a, nan=True):
    
    # Check whether examples and attributes have the same lengths.
    if len(Ex) != len(a):
        raise ValueError("Ex and a must be of the same size.")

    # Compute information gain ratio as IG/IV
    return info_gain(Ex, a, nan) / intrinsic_value(Ex, a, nan)

In [19]:
ar=[]
br=[]
for (columnName, columnData) in X.iteritems():
        a=info_gain_ratio(columnData, y)
        ar.append(a)
        br.append(columnName)
a1 = pd.DataFrame(ar)
b1 = pd.DataFrame(br)
info2 = pd.concat([a1,b1], axis=1)
info2.columns = ['Score','Features']
info2

        Score                   Features
0    0.020593                     gender
1    0.681085                        PPE
2    0.686418                        DFA
3    0.688661                       RPDE
4    0.353334                  numPulses
..        ...                        ...
748  0.686418  tqwt_kurtosisValue_dec_32
749  0.688661  tqwt_kurtosisValue_dec_33
750  0.693147  tqwt_kurtosisValue_dec_34
751  0.690904  tqwt_kurtosisValue_dec_35
752  0.693147  tqwt_kurtosisValue_dec_36

[753 rows x 2 columns]

In [20]:
top2 = info2.nlargest(50,'Score')
SelectedFeatures2= np.array(top2['Features'])
SelectedFeatures2

array(['b4', 'mean_MFCC_8th_coef', 'mean_0th_delta', 'mean_1st_delta',
       'mean_11th_delta', 'std_6th_delta', 'det_entropy_log_6_coef',
       'det_TKEO_mean_5_coef', 'det_TKEO_std_3_coef',
       'app_entropy_log_4_coef', 'app_entropy_log_10_coef',
       'det_LT_entropy_shannon_1_coef', 'det_LT_entropy_log_9_coef',
       'det_LT_TKEO_std_8_coef', 'app_LT_TKEO_mean_4_coef',
       'app_LT_TKEO_std_4_coef', 'tqwt_energy_dec_9',
       'tqwt_energy_dec_10', 'tqwt_energy_dec_14', 'tqwt_energy_dec_20',
       'tqwt_energy_dec_21', 'tqwt_entropy_shannon_dec_4',
       'tqwt_entropy_shannon_dec_13', 'tqwt_TKEO_mean_dec_14',
       'tqwt_TKEO_mean_dec_16', 'tqwt_TKEO_mean_dec_25',
       'tqwt_TKEO_std_dec_26', 'tqwt_stdValue_dec_20',
       'tqwt_stdValue_dec_30', 'tqwt_stdValue_dec_34',
       'tqwt_stdValue_dec_35', 'tqwt_minValue_dec_5',
       'tqwt_minValue_dec_7', 'tqwt_minValue_dec_13',
       'tqwt_maxValue_dec_20', 'tqwt_maxValue_dec_25',
       'tqwt_maxValue_dec_26', 'tqwt_maxValue_dec_36',
       'tqwt_skewnessValue_dec_6', 'tqwt_skewnessValue_dec_36',
       'tqwt_kurtosisValue_dec_2', 'tqwt_kurtosisValue_dec_3',
       'tqwt_kurtosisValue_dec_6', 'tqwt_kurtosisValue_dec_11',
       'meanPeriodPulses', 'minIntensity', 'maxIntensity',
       'meanIntensity', 'f1', 'f2'], dtype=object)

In [21]:
#Symmetrical Uncertainty Calculation

#entropy
def entropy(Y):
    unique, count = np.unique(Y, return_counts=True, axis=0)
    prob = count/len(Y)
    en = np.sum((-1)*prob*np.log2(prob))
    return en

#Joint Entropy
def jEntropy(Y,X):
    YX = np.c_[Y,X]
    return entropy(YX)

#conditional entropy
def cEntropy(Y, X):
    return jEntropy(Y, X) - entropy(X)

#gain
def gain(Y, X):
    return entropy(Y) - cEntropy(Y,X)

#SU
def symmetricalUncertain(Y,X):
    n = float(y.shape[0])
    vals = np.unique(Y)
    # Computing Entropy for the feature x. 
    Hx = entropy(X)
    # Computing Entropy for the feature y.
    Hy = entropy(Y)
    #Computing Joint entropy between x and y.
    Hxy = jEntropy(Y,X)
    IG = Hx-Hxy
    return 2*IG/(Hx+Hy)

In [22]:
top_n1 =[]
for i in X.columns.values:
    X[i]=X[i].astype('float64')
    y=y.astype('float64')
    top_n1.append(symmetricalUncertain(X[i],y))
    
col_name1 = np.array(X.columns)
a1 = pd.DataFrame(top_n1)
b1 = pd.DataFrame(col_name1)
info3 = pd.concat([a1,b1], axis=1)
info3.columns = ['Score','Features']
info3

        Score                   Features
0   -1.073311                     gender
1   -1.686393                        PPE
2   -1.685608                        DFA
3   -1.685339                       RPDE
4   -1.720568                  numPulses
..        ...                        ...
748 -1.685930  tqwt_kurtosisValue_dec_32
749 -1.685660  tqwt_kurtosisValue_dec_33
750 -1.684720  tqwt_kurtosisValue_dec_34
751 -1.685230  tqwt_kurtosisValue_dec_35
752 -1.684800  tqwt_kurtosisValue_dec_36

[753 rows x 2 columns]

In [23]:
top3 = info3.nlargest(50,'Score')
SelectedFeatures3 = np.array(top3['Features'])
SelectedFeatures3

array(['gender', 'Ea2', 'GQ_prc5_95', 'tqwt_medianValue_dec_17',
       'GQ_std_cycle_closed', 'tqwt_medianValue_dec_24',
       'tqwt_medianValue_dec_16', 'tqwt_medianValue_dec_25',
       'tqwt_medianValue_dec_20', 'tqwt_medianValue_dec_5',
       'tqwt_skewnessValue_dec_5', 'tqwt_medianValue_dec_30',
       'tqwt_medianValue_dec_26', 'tqwt_medianValue_dec_18',
       'tqwt_medianValue_dec_21', 'tqwt_medianValue_dec_34',
       'tqwt_skewnessValue_dec_3', 'tqwt_TKEO_std_dec_12',
       'tqwt_stdValue_dec_3', 'std_6th_delta', 'tqwt_TKEO_mean_dec_16',
       'tqwt_TKEO_mean_dec_9', 'tqwt_TKEO_mean_dec_12',
       'tqwt_medianValue_dec_33', 'tqwt_energy_dec_18',
       'tqwt_TKEO_std_dec_18', 'tqwt_stdValue_dec_1',
       'tqwt_minValue_dec_20', 'tqwt_medianValue_dec_22', 'IMF_NSR_SEO',
       'mean_8th_delta_delta', 'mean_MFCC_10th_coef', 'IMF_NSR_TKEO',
       'std_MFCC_0th_coef', 'std_1st_delta',
       'det_LT_entropy_shannon_4_coef', 'det_LT_TKEO_mean_8_coef',
       'app_LT_entropy_log_6_coef', 'tqwt_energy_dec_13',
       'tqwt_energy_dec_15', 'tqwt_TKEO_mean_dec_17',
       'tqwt_TKEO_std_dec_14', 'tqwt_TKEO_std_dec_15',
       'tqwt_stdValue_dec_6', 'tqwt_minValue_dec_2',
       'tqwt_minValue_dec_8', 'tqwt_minValue_dec_27',
       'tqwt_maxValue_dec_28', 'tqwt_skewnessValue_dec_7',
       'tqwt_skewnessValue_dec_24'], dtype=object)

In [46]:
from functools import reduce
def top_fs_union(n):
    f1 = SelectedFeatures1[:n]
    f2 = SelectedFeatures2[:n]
    f3 = SelectedFeatures3[:n]
    f_3k = reduce(np.union1d, (f1,f2,f3))
    f_2k = ((len(f_3k)*2)//3)
    f_2k_random = np.random.choice(f_3k,f_2k,replace=False)
    f_5k = reduce(np.union1d, (f_3k,f_2k_random))
    return(f_5k)

In [45]:
f1 = SelectedFeatures1[:5]
f2 = SelectedFeatures2[:5]
f3 = SelectedFeatures3[:5]
f_3k = reduce(np.union1d, (f1,f2,f3))
f_2k = ((len(f_3k)*2)//3)
f_2k_random = np.random.choice(f_3k,f_2k,replace=False)
f_5k = reduce(np.union1d, (f_3k,f_2k_random))
f_5k

array(['Ea2', 'GQ_prc5_95', 'GQ_std_cycle_closed', 'b4', 'gender',
       'mean_0th_delta', 'mean_11th_delta', 'mean_1st_delta',
       'mean_MFCC_2nd_coef', 'mean_MFCC_8th_coef', 'std_9th_delta_delta',
       'tqwt_medianValue_dec_17', 'tqwt_minValue_dec_11',
       'tqwt_minValue_dec_12', 'tqwt_minValue_dec_13'], dtype=object)

In [49]:
def assemble_run(n,classifier,test_size):
  top_fs=top_fs_union(n)
  top_fs=np.append(top_fs,['Class'], axis=0)
  df = data.loc[:,top_fs]
  X = df.drop(['Class'], axis=1)
  y = df['Class']
  from sklearn.model_selection import train_test_split
  x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=test_size)
  model = classifier()#modify the code ,keep classifier in different function and call here
  model.fit(x_train, y_train)
  print (model.score(x_test,y_test))

In [50]:
#SUPPORT VECTOR MACHINE
#Feature Subset by Union of 5 Best Features from each
SVM5  = assemble_run(5,SVC,.5)
#Feature Subset by Union of 10 Best Features from each
SVM10 = assemble_run(10,SVC,.5)
#Feature Subset by Union of 20 Best Features from each
SVM20 = assemble_run(20,SVC,.5)
#Feature Subset by Union of 30 Best Features from each
SVM30 = assemble_run(30,SVC,.5)
#Feature Subset by Union of 40 Best Features from each
SVM40 = assemble_run(40,SVC,.5)
#Feature Subset by Union of 50 Best Features from each
SVM50 = assemble_run(50,SVC,.5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

0.7222222222222222
0.7301587301587301
0.753968253968254
0.7645502645502645
0.7486772486772487
0.7566137566137566

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [51]:
#K-NEAREST NEIGHBOUR
#Feature Subset by Union of 5 Best Features from each
KNN5 = assemble_run(5,KNeighborsClassifier,.5)
#Feature Subset by Union of 10 Best Features from each
KNN10 = assemble_run(10,KNeighborsClassifier,.5)
#Feature Subset by Union of 20 Best Features from each
KNN20 = assemble_run(20,KNeighborsClassifier,.5)
#Feature Subset by Union of 30 Best Features from each
KNN30 = assemble_run(30,KNeighborsClassifier,.5)
#Feature Subset by Union of 40 Best Features from each
KNN40 = assemble_run(40,KNeighborsClassifier,.5)
#Feature Subset by Union of 50 Best Features from each
KNN50 = assemble_run(50,KNeighborsClassifier,.5)

0.6772486772486772
0.7063492063492064
0.701058201058201
0.7248677248677249
0.7275132275132276
0.7222222222222222

In [52]:
#DECISION TREE
#Feature Subset by Union of 5 Best Features from each
DT5  = assemble_run(5,DecisionTreeClassifier,.5)
#Feature Subset by Union of 10 Best Features from each
DT10 = assemble_run(10,DecisionTreeClassifier,.5)
#Feature Subset by Union of 20 Best Features from each
DT20 = assemble_run(20,DecisionTreeClassifier,.5)
#Feature Subset by Union of 30 Best Features from each
DT30 = assemble_run(30,DecisionTreeClassifier,.5)
#Feature Subset by Union of 40 Best Features from each
DT40 = assemble_run(40,DecisionTreeClassifier,.5)
#Feature Subset by Union of 50 Best Features from each
DT50 = assemble_run(50,DecisionTreeClassifier,.5)

0.7142857142857143
0.7354497354497355
0.7857142857142857
0.7671957671957672
0.7936507936507936
0.7328042328042328

In [53]:
#NAIVE BAYES
#Feature Subset by Union of 5 Best Features from each
NB5  = assemble_run(5,GaussianNB,.5)
#Feature Subset by Union of 10 Best Features from each
NB10 = assemble_run(10,GaussianNB,.5)
#Feature Subset by Union of 20 Best Features from each
NB20 = assemble_run(20,GaussianNB,.5)
#Feature Subset by Union of 30 Best Features from each
NB30 = assemble_run(30,GaussianNB,.5)
#Feature Subset by Union of 40 Best Features from each
NB40 = assemble_run(40,GaussianNB,.5)
#Feature Subset by Union of 50 Best Features from each
NB50 = assemble_run(50,GaussianNB,.5)

0.7883597883597884
0.7936507936507936
0.783068783068783
0.7433862433862434
0.746031746031746
0.7513227513227513